# Generated by Django 4.0.3 on 2023-06-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='barrier_free_hotel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('FCLTY_NM', models.CharField(max_length=60)),
                ('RDNMADR_NM', models.CharField(max_length=60)),
                ('CTPRVN_CD', models.IntegerField()),
                ('SIGNGU_CD', models.IntegerField()),
                ('FCLTY_LO', models.FloatField()),
                ('FCLTY_LA', models.FloatField()),
                ('AREA_NM', models.CharField(max_length=60)),
                ('HMPG_URL', models.CharField(max_length=60)),
                ('HOTEL_GRAD_NO', models.CharField(max_length=40)),
                ('TEL_NO', models.CharField(max_length=60)),
                ('GSRM_CO', models.FloatField()),
                ('GSRM_AR_VALUE', models.CharField(max_length=60)),
                ('GSRM_SVC_POSBL_AT', models.CharField(max_length=60)),
                ('DSPSN_FCLTY_AT', models.CharField(max_length=60)),
                ('BASE_DE', models.CharField(max_length=60)),
            ],
        ),
    ]
