# Generated by Django 4.0.3 on 2023-06-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrier_free_hotel',
            name='AREA_NM',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='barrier_free_hotel',
            name='BASE_DE',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='barrier_free_hotel',
            name='DSPSN_FCLTY_AT',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='barrier_free_hotel',
            name='FCLTY_NM',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='barrier_free_hotel',
            name='GSRM_AR_VALUE',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='barrier_free_hotel',
            name='GSRM_SVC_POSBL_AT',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='barrier_free_hotel',
            name='HMPG_URL',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='barrier_free_hotel',
            name='HOTEL_GRAD_NO',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='barrier_free_hotel',
            name='RDNMADR_NM',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='barrier_free_hotel',
            name='TEL_NO',
            field=models.CharField(max_length=100),
        ),
    ]
