# Generated by Django 4.0.3 on 2023-06-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_barrier_free_hotel_area_nm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorized',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('addr1', models.CharField(max_length=100)),
                ('addr2', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('contentid', models.IntegerField()),
                ('contenttypeid', models.IntegerField()),
                ('firstimage', models.CharField(max_length=100)),
                ('firstimage2', models.CharField(max_length=100)),
                ('mapx', models.FloatField()),
                ('mapy', models.FloatField()),
                ('tel', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
