# Generated by Django 4.0.3 on 2023-06-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_categorized_contentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrier_free_hotel',
            name='AREA_NM',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='barrier_free_hotel',
            name='BASE_DE',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='barrier_free_hotel',
            name='CTPRVN_CD',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='barrier_free_hotel',
            name='DSPSN_FCLTY_AT',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='barrier_free_hotel',
            name='FCLTY_LA',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='barrier_free_hotel',
            name='FCLTY_LO',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='barrier_free_hotel',
            name='FCLTY_NM',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='barrier_free_hotel',
            name='GSRM_AR_VALUE',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='barrier_free_hotel',
            name='GSRM_CO',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='barrier_free_hotel',
            name='GSRM_SVC_POSBL_AT',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='barrier_free_hotel',
            name='HMPG_URL',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='barrier_free_hotel',
            name='HOTEL_GRAD_NO',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='barrier_free_hotel',
            name='RDNMADR_NM',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='barrier_free_hotel',
            name='SIGNGU_CD',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='barrier_free_hotel',
            name='TEL_NO',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
