# Generated by Django 4.0.3 on 2023-06-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_barrier_free_hotel_area_nm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='transfortation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentid', models.IntegerField(null=True)),
                ('parking', models.CharField(max_length=500, null=True)),
                ('route', models.CharField(max_length=500, null=True)),
                ('publictransport', models.CharField(max_length=500, null=True)),
                ('ticketoffice', models.CharField(max_length=500, null=True)),
                ('promotion', models.CharField(max_length=500, null=True)),
                ('wheelchair', models.CharField(max_length=500, null=True)),
                ('exit', models.CharField(max_length=500, null=True)),
                ('elevator', models.CharField(max_length=500, null=True)),
                ('restroom', models.CharField(max_length=500, null=True)),
                ('auditorium', models.CharField(max_length=500, null=True)),
                ('room', models.CharField(max_length=500, null=True)),
                ('handicapetc', models.CharField(max_length=500, null=True)),
                ('braileblock', models.CharField(max_length=500, null=True)),
                ('helpdog', models.CharField(max_length=500, null=True)),
                ('guidehuman', models.CharField(max_length=500, null=True)),
                ('audioguide', models.CharField(max_length=500, null=True)),
                ('bigprint', models.CharField(max_length=500, null=True)),
                ('brailepromotion', models.CharField(max_length=500, null=True)),
                ('guidesystem', models.CharField(max_length=500, null=True)),
                ('blindhandicapetc', models.CharField(max_length=500, null=True)),
                ('singuide', models.CharField(max_length=500, null=True)),
                ('videoguide', models.CharField(max_length=500, null=True)),
                ('hearingroom', models.CharField(max_length=500, null=True)),
                ('hearinghandicapetc', models.CharField(max_length=500, null=True)),
                ('stroller', models.CharField(max_length=500, null=True)),
                ('lactationroom', models.CharField(max_length=500, null=True)),
                ('babysparechair', models.CharField(max_length=500, null=True)),
                ('infantsfamilyetc', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
