# Generated by Django 4.0.3 on 2023-06-10 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_transfortation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='transfortation',
            new_name='transportation',
        ),
    ]
