# Generated by Django 4.0.3 on 2023-06-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_transfortation_transportation'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorized',
            name='audioguide',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorized',
            name='auditorium',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorized',
            name='babysparechair',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorized',
            name='bigprint',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorized',
            name='blindhandicapetc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorized',
            name='braileblock',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorized',
            name='brailepromotion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorized',
            name='elevator',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorized',
            name='exit',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorized',
            name='guidehuman',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorized',
            name='guidesystem',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorized',
            name='handicapetc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorized',
            name='hearinghandicapetc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorized',
            name='hearingroom',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorized',
            name='helpdog',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorized',
            name='infantsfamilyetc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorized',
            name='lactationroom',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorized',
            name='parking',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorized',
            name='promotion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorized',
            name='publictransport',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorized',
            name='restroom',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorized',
            name='room',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorized',
            name='route',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorized',
            name='singuide',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorized',
            name='stroller',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorized',
            name='ticketoffice',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorized',
            name='videoguide',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorized',
            name='wheelchair',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
